<#
.SYNOPSIS
    Compiles the two launcher executables using MinGW-w64 from build-cache/tools.

.DESCRIPTION
    Invokes windres + gcc twice:

      1. ReportAnonymizer.exe        : subsystem WINDOWS, GUI launcher.
      2. report-anonymizer-cli.exe   : subsystem CONSOLE, CLI launcher.

    Both binaries embed:
      - the multi-resolution app_icon.ico (so File Explorer / taskbar / Alt-
        Tab show the proper icon)
      - the launcher.manifest (UAC asInvoker, DPI awareness, longPathAware,
        UTF-8 active code page)
      - a VS_VERSION_INFO block with the version supplied by -Version
        (default: parsed from <repo>/pyproject.toml).

    Static linking of libgcc/libstdc++ is requested via -static so the
    resulting .exe has zero external runtime dependencies (it must work on
    a fresh Windows 10 1809+ install with no Visual C++ runtime installed).

.PARAMETER Version
    Optional version string (e.g. "1.0.0"). Parsed from pyproject.toml if
    omitted.

.PARAMETER ToolsRoot
    Optional override for the MinGW toolchain root.
#>
[CmdletBinding()]
param(
    [string]$Version,
    [string]$ToolsRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Definition
$WindowsRoot = Split-Path -Parent $ScriptDir
$RepoRoot    = Split-Path -Parent (Split-Path -Parent $WindowsRoot)
$LauncherDir = Join-Path $WindowsRoot 'launcher'

if (-not $ToolsRoot) { $ToolsRoot = Join-Path $WindowsRoot 'build-cache\tools' }
$MingwBin   = Join-Path $ToolsRoot 'mingw64\bin'
$Gcc        = Join-Path $MingwBin 'gcc.exe'
$Windres    = Join-Path $MingwBin 'windres.exe'

if (-not (Test-Path -LiteralPath $Gcc))     { throw "gcc.exe not found: $Gcc. Run bootstrap-tools.ps1 first." }
if (-not (Test-Path -LiteralPath $Windres)) { throw "windres.exe not found: $Windres" }

if (-not (Test-Path -LiteralPath (Join-Path $LauncherDir 'app_icon.ico'))) {
    throw "app_icon.ico missing under $LauncherDir. Run convert-assets.ps1 first."
}

# ---------------------------------------------------------------------------
# Version resolution.
# ---------------------------------------------------------------------------
if (-not $Version) {
    $pyproject = Join-Path $RepoRoot 'pyproject.toml'
    if (Test-Path -LiteralPath $pyproject) {
        $m = Select-String -LiteralPath $pyproject -Pattern '^version\s*=\s*"(?<v>[^"]+)"' -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($m) { $Version = $m.Matches[0].Groups['v'].Value }
    }
}
if (-not $Version) { $Version = '0.0.0' }

# Convert 1.0.0 or 1.0.0-rc1 to a 4-tuple acceptable to VS_VERSION_INFO.
$verCore = ($Version -split '[-+]')[0]
$verParts = ($verCore -split '\.') + @('0','0','0','0') | Select-Object -First 4
$verQuad = $verParts -join ','
$verStr  = ($verParts -join '.')

Write-Host "[compile-launchers] version: $verStr (quad: $verQuad)" -ForegroundColor DarkGray

Push-Location $LauncherDir
try {
    # -----------------------------------------------------------------------
    # 1. Compile the resource scripts. The two launchers want different
    #    OriginalFilename strings in the version info, so each gets its own
    #    .res file.
    #
    #    PowerShell 5.1 mangles backslash-quote sequences when forwarding
    #    arguments to native commands, which broke the previous
    #    "-DRA_APP_VERSION_STR=\""$verStr\""" approach (windres saw a torn
    #    quote and reported "syntax error" inside VS_VERSION_INFO). To dodge
    #    the issue entirely we generate a per-target .rc copy with the
    #    placeholders already substituted by PowerShell, then point windres
    #    at the substituted file.
    # -----------------------------------------------------------------------
    $rcSourcePath = Join-Path $LauncherDir 'app_icon.rc'
    if (-not (Test-Path -LiteralPath $rcSourcePath)) {
        throw "Source resource script missing: $rcSourcePath"
    }
    $rcSource = Get-Content -LiteralPath $rcSourcePath -Raw

    function New-Rc([hashtable]$Substitutions, [string]$OutFile) {
        # Inject concrete #define lines right after the existing
        # #include <winver.h>. The .rc source guards every macro behind a
        # `#ifndef ... #define ... #endif` block; once we have already
        # defined the symbol, every guard becomes a no-op and the rest of
        # the file (the VS_VERSION_INFO block, ICON / RT_MANIFEST lines)
        # is consumed verbatim by windres.
        $defineLines = ($Substitutions.Keys | Sort-Object | ForEach-Object {
            "#define {0} {1}" -f $_, $Substitutions[$_]
        }) -join "`r`n"
        $injection = "`r`n/* Generated by compile-launchers.ps1; do not edit. */`r`n" + $defineLines + "`r`n"
        $rendered = $rcSource -replace '(?m)^(#include\s+<winver\.h>)\s*$', ('$1' + $injection)
        Set-Content -LiteralPath $OutFile -Value $rendered -Encoding ASCII
    }

    function Invoke-Windres([string]$rcFile, [string]$outFile) {
        Write-Host "  -> windres $rcFile -> $outFile" -ForegroundColor DarkGray
        & $Windres -O coff -i $rcFile -o $outFile
        if ($LASTEXITCODE -ne 0) { throw "windres failed on $rcFile (exit $LASTEXITCODE)" }
    }

    $guiRc = Join-Path $LauncherDir 'app_icon_gui.gen.rc'
    $cliRc = Join-Path $LauncherDir 'app_icon_cli.gen.rc'
    New-Rc -OutFile $guiRc -Substitutions @{
        'RA_APP_VERSION_STR'       = '"' + $verStr + '"'
        'RA_APP_VERSION_QUAD'      = $verQuad
        'RA_APP_PRODUCT'           = '"Report Anonymizer"'
        'RA_APP_COMPANY'           = '"nemmusu"'
        'RA_APP_FILE_DESCRIPTION'  = '"Report Anonymizer launcher"'
        'RA_APP_INTERNAL_NAME'     = '"ReportAnonymizer"'
        'RA_APP_ORIGINAL_FILENAME' = '"ReportAnonymizer.exe"'
    }
    New-Rc -OutFile $cliRc -Substitutions @{
        'RA_APP_VERSION_STR'       = '"' + $verStr + '"'
        'RA_APP_VERSION_QUAD'      = $verQuad
        'RA_APP_PRODUCT'           = '"Report Anonymizer"'
        'RA_APP_COMPANY'           = '"nemmusu"'
        'RA_APP_FILE_DESCRIPTION'  = '"Report Anonymizer CLI"'
        'RA_APP_INTERNAL_NAME'     = '"ReportAnonymizerCLI"'
        'RA_APP_ORIGINAL_FILENAME' = '"report-anonymizer-cli.exe"'
    }

    Invoke-Windres -rcFile $guiRc -outFile (Join-Path $LauncherDir 'app_icon_gui.res')
    Invoke-Windres -rcFile $cliRc -outFile (Join-Path $LauncherDir 'app_icon_cli.res')

    # -----------------------------------------------------------------------
    # 2. Compile each launcher. -municode promotes wmain / wWinMain to the
    #    entry points; -static gives us a dependency-free .exe.
    # -----------------------------------------------------------------------
    $commonFlags = @(
        '-O2',
        '-municode',
        '-Wall',
        '-Wextra',
        '-static',
        '-D_UNICODE',
        '-DUNICODE'
    )
    $commonLibs = @('-lshell32', '-luser32', '-lkernel32')

    Write-Host "  -> gcc -mwindows launcher_gui.c -> ReportAnonymizer.exe" -ForegroundColor DarkGray
    & $Gcc -mwindows @commonFlags 'launcher_gui.c' 'app_icon_gui.res' '-o' 'ReportAnonymizer.exe' @commonLibs
    if ($LASTEXITCODE -ne 0) { throw "gcc failed compiling launcher_gui.c (exit $LASTEXITCODE)" }

    Write-Host "  -> gcc           launcher_cli.c -> report-anonymizer-cli.exe" -ForegroundColor DarkGray
    & $Gcc @commonFlags 'launcher_cli.c' 'app_icon_cli.res' '-o' 'report-anonymizer-cli.exe' @commonLibs
    if ($LASTEXITCODE -ne 0) { throw "gcc failed compiling launcher_cli.c (exit $LASTEXITCODE)" }

    # Sanity check.
    foreach ($exe in @('ReportAnonymizer.exe', 'report-anonymizer-cli.exe')) {
        $abs = Join-Path $LauncherDir $exe
        if (-not (Test-Path -LiteralPath $abs)) {
            throw "Expected output missing: $abs"
        }
        $size = (Get-Item -LiteralPath $abs).Length
        Write-Host ("  -> {0,-32} {1,8:N0} bytes" -f $exe, $size) -ForegroundColor Green
    }
} finally {
    Pop-Location
}

Write-Host "[compile-launchers] OK" -ForegroundColor Green
