<#
.SYNOPSIS
    Freezes the staging Python tree's pip install graph into
    requirements-lock-windows.txt (repo root). Implements plan §2.4.bis.

.DESCRIPTION
    Runs `python.exe -m pip freeze` against the embeddable Python under
    staging/app/python/ and writes the result to <repo>/requirements-lock-windows.txt
    with a comment header explaining what the file is for and how to refresh
    it. The CI build (Fase 5) will then use this lockfile via
    `pip install -r requirements-lock-windows.txt --require-hashes` to
    guarantee a reproducible build.

    The script is idempotent. If the new freeze output exactly matches the
    file already on disk (excluding the header), no rewrite occurs.

.PARAMETER StagingRoot
    Optional override for the staging root.

.PARAMETER OutputPath
    Optional override for the lockfile destination.
#>
[CmdletBinding()]
param(
    [string]$StagingRoot,
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Definition
$WindowsRoot = Split-Path -Parent $ScriptDir
$RepoRoot    = Split-Path -Parent (Split-Path -Parent $WindowsRoot)

if (-not $StagingRoot) { $StagingRoot = Join-Path $WindowsRoot 'staging' }
if (-not $OutputPath)  { $OutputPath  = Join-Path $RepoRoot 'requirements-lock-windows.txt' }

$PyExe = Join-Path $StagingRoot 'app\python\python.exe'
if (-not (Test-Path -LiteralPath $PyExe)) {
    throw "Staging Python missing at $PyExe. Run build-python-tree.ps1 first."
}

Write-Host "[freeze-lockfile] pip freeze on $PyExe" -ForegroundColor Cyan
$frozen = & $PyExe -m pip freeze --disable-pip-version-check 2>&1
if ($LASTEXITCODE -ne 0) {
    throw "pip freeze failed (exit $LASTEXITCODE):`n$frozen"
}

# Filter: drop pip's own self-line + drop any editable installs (which
# wouldn't be reproducible from the lockfile anyway).
$lines = $frozen `
    | Where-Object { $_ -is [string] } `
    | Where-Object { $_ -notmatch '^\s*#' } `
    | Where-Object { $_ -notmatch '^-e\s+' } `
    | Sort-Object

$timestamp = (Get-Date -Format 'yyyy-MM-ddTHH:mm:ssK')
$header = @"
# requirements-lock-windows.txt
#
# Auto-generated by packaging/windows/scripts/freeze-lockfile.ps1 from the
# Python embeddable tree that ships inside the Report Anonymizer Windows
# installer. DO NOT edit by hand: regenerate via
#
#     pwsh -ExecutionPolicy Bypass -File packaging\windows\build.ps1 -Version <ver>
#
# (or run scripts\freeze-lockfile.ps1 directly after build-python-tree.ps1).
#
# The CI workflow build-windows.yml (Fase 5) consumes this file via
#     pip install -r requirements-lock-windows.txt --require-hashes
# to guarantee a byte-for-byte reproducible Setup.exe. Refreshing the lock
# file is intentional: bump it whenever requirements.txt is updated.
#
# Last regenerated: $timestamp
# Source interpreter: $PyExe
#
"@

$payload = $header + ($lines -join "`r`n") + "`r`n"

if (Test-Path -LiteralPath $OutputPath) {
    $existing = Get-Content -LiteralPath $OutputPath -Raw
    # Compare only the non-header lines so that a timestamp delta alone does
    # not trigger a rewrite (and noisy diffs in PRs).
    $existingBody = ($existing -split "`n" | Where-Object { $_ -notmatch '^\s*#' -and $_.Trim() }) -join "`r`n"
    $newBody      = ($lines) -join "`r`n"
    if ($existingBody -eq $newBody) {
        Write-Host "[freeze-lockfile] lockfile unchanged (skip rewrite)" -ForegroundColor Green
        return
    }
}

Set-Content -LiteralPath $OutputPath -Value $payload -Encoding UTF8
Write-Host "[freeze-lockfile] wrote $OutputPath ($(($lines | Measure-Object).Count) packages)" -ForegroundColor Green
